/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.github.rahulsom.waena

import org.assertj.core.api.Assertions.assertThat
import org.gradle.testfixtures.ProjectBuilder
import kotlin.test.Test

/**
 * A simple unit test for the 'com.github.rahulsom.waena.greeting' plugin.
 */
class WaenaPluginTest {
  @Test
  fun `plugin registers task`() {
    // Create a test project and apply the plugin
    val project = ProjectBuilder.builder().build()
    project.plugins.apply(WaenaRootPlugin::class.java)
    project.plugins.apply(WaenaPublishedPlugin::class.java)

    // Verify the result
    assertThat(project.tasks.map { it.name }).contains("publishToSonatype")
  }
}
