name: Build Main

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: gradle/actions/wrapper-validation@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17
          cache: gradle

      - run: ./gradlew build --stacktrace --parallel --scan
