name: Build PR

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        jdk: ['17', '21']

    steps:
      - uses: actions/checkout@v4

      - uses: gradle/wrapper-validation-action@v3
        name: Validate Gradle Wrapper

      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.jdk }}
          cache: gradle

      - run: ./gradlew build --stacktrace --parallel --scan
