name: Build

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
    tags: [ 'v[0-9]+.[0-9]+.[0-9]+' ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        jdk: ${{ github.event_name == 'pull_request' && fromJSON('["17", "21"]') || fromJSON('["17"]') }}

    steps:
      - uses: actions/checkout@v5

      - uses: gradle/actions/wrapper-validation@v4

      - uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.jdk }}
          cache: gradle

      - name: Build (PR)
        if: github.event_name == 'pull_request'
        run: ./gradlew build --stacktrace --parallel --scan

      - name: Build (Main)
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: ./gradlew build --stacktrace --parallel --scan

      - name: Build (Release)
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
        env:
          GRADLE_PUBLISH_KEY: ${{ secrets.GRADLE_PUBLISH_KEY }}
          GRADLE_PUBLISH_SECRET: ${{ secrets.GRADLE_PUBLISH_SECRET }}
        run: |
          ./gradlew -Prelease.useLastTag=true build final --stacktrace --scan