name: Build PR

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        jdk: ['8', '11']

    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4

      - name: Cache Gradle Caches
        id: cache-gradle-caches
        uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-${{hashFiles('**/*.gradle')}}
          path: |
            ~/.gradle/caches
      - name: Cache Gradle Wrapper
        id: cache-gradle-wrapper
        uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
          path: |
            ~/.gradle/wrapper
      - uses: gradle/wrapper-validation-action@v1
        name: Validate Gradle Wrapper

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.jdk }}

      - name: Build with Gradle
        run: ./gradlew build --stacktrace --parallel --scan
